export interface Challenge {
  title: string;
  category: 'physical' | 'mental' | 'personal' | 'relationships';
  days: number; // 1, 7, 30, etc
  reward: string; // coin description or amount
}

export const CHALLENGE_GOALS: Challenge[] = [
  // Physical
  { title: "Do 50 Pushups Over 1 Day", category: 'physical', days: 1, reward: "5-15 Coins" },
  { title: "Do 100 Pushups Over 2 Days", category: 'physical', days: 2, reward: "5-15 Coins" },
  { title: "Do 150 Pushups Over 3 Days", category: 'physical', days: 3, reward: "5-15 Coins" },
  { title: "Do 200 Pushups Over 3 Days", category: 'physical', days: 3, reward: "5-15 Coins" },
  { title: "Do 10 Pull Ups / Handstand Pushups Over 1 Day", category: 'physical', days: 1, reward: "5-15 Coins" },
  { title: "Do 20 Pull Ups / Handstand Pushups Over 2 Days", category: 'physical', days: 2, reward: "5-15 Coins" },
  { title: "Do 30 Pull Ups / Handstand Pushups Over 3 Days", category: 'physical', days: 3, reward: "5-15 Coins" },
  { title: "Do 40 Pull Ups / Handstand Pushups Over 3 Days", category: 'physical', days: 3, reward: "5-15 Coins" },
  { title: "Do 100 Squats Over 1 Day", category: 'physical', days: 1, reward: "5-15 Coins" },
  { title: "Do 150 Squats Over 2 Days", category: 'physical', days: 2, reward: "5-15 Coins" },
  { title: "Do 200 Squats Over 3 Days", category: 'physical', days: 3, reward: "5-15 Coins" },
  { title: "Do 300 Squats Over 3 Days", category: 'physical', days: 3, reward: "5-15 Coins" },
  { title: "Run a Mile Under 5 Minutes", category: 'physical', days: 1, reward: "5-10 Coins" },
  { title: "Run a Mile Under 6 Minutes", category: 'physical', days: 1, reward: "5-10 Coins" },
  { title: "Run a Mile Under 7 Minutes", category: 'physical', days: 1, reward: "5-10 Coins" },
  { title: "Run a Mile Under 8 Minutes", category: 'physical', days: 1, reward: "5-10 Coins" },
  { title: "Run a Mile Under 10 Minutes", category: 'physical', days: 1, reward: "5-10 Coins" },
  { title: "Run 1 Mile in 1 Day", category: 'physical', days: 1, reward: "12 Coins" },
  { title: "Run 2 Miles in 1 Day", category: 'physical', days: 1, reward: "14 Coins" },
  { title: "Run 3 Miles in 1 Day", category: 'physical', days: 1, reward: "16 Coins" },
  { title: "Run 4 Miles in 1 Day", category: 'physical', days: 1, reward: "18 Coins" },
  { title: "Run 5 Miles in 1 Day", category: 'physical', days: 1, reward: "20 Coins" },
  { title: "Run 10 Miles Over 7 Days", category: 'physical', days: 7, reward: "20 Coins" },
  { title: "Run 20 Miles Over 7 Days", category: 'physical', days: 7, reward: "30 Coins" },
  { title: "Run 30 Miles Over 7 Days", category: 'physical', days: 7, reward: "40 Coins" },
  { title: "Swim 3 Laps in 1 Day", category: 'physical', days: 1, reward: "5 Coins" },
  { title: "Swim 10 Laps Over 7 Days", category: 'physical', days: 7, reward: "20 Coins" },
  { title: "Swim 20 Laps Over 7 Days", category: 'physical', days: 7, reward: "30 Coins" },
  { title: "Swim 30 Laps Over 7 Days", category: 'physical', days: 7, reward: "40 Coins" },
  { title: "Go Hiking in 1 Day", category: 'physical', days: 1, reward: "10 Coins" },
  { title: "Go Biking in 1 Day", category: 'physical', days: 1, reward: "10 Coins" },
  { title: "Join a Sports Meet-Up Over 7 Days", category: 'physical', days: 7, reward: "15 Coins" },
  { title: "Win a Race Over 7 Days", category: 'physical', days: 7, reward: "20 Coins" },

  // Mental
  { title: "Wake Up Before 5am in 1 Day", category: 'mental', days: 1, reward: "5-10 Coins" },
  { title: "Wake Up Before 6am in 1 Day", category: 'mental', days: 1, reward: "5-10 Coins" },
  { title: "Wake Up Before 7am in 1 Day", category: 'mental', days: 1, reward: "5-10 Coins" },
  { title: "Wake Up Before 8am in 1 Day", category: 'mental', days: 1, reward: "5-10 Coins" },
  { title: "Wake Up Before 9am in 1 Day", category: 'mental', days: 1, reward: "5-10 Coins" },
  { title: "Sleep 7+ Hours in 1 Day", category: 'mental', days: 1, reward: "5-15 Coins" },
  { title: "Sleep 8+ Hours in 1 Day", category: 'mental', days: 1, reward: "5-15 Coins" },
  { title: "Sleep 9+ Hours in 1 Day", category: 'mental', days: 1, reward: "5-15 Coins" },
  { title: "Read 3-10 Pages of a Book in 1 Day", category: 'mental', days: 1, reward: "5 Coins" },
  { title: "Read a Full Book Over 7 Days", category: 'mental', days: 7, reward: "20 Coins" },
  { title: "Do 10 Deep Breaths in 1 Day", category: 'mental', days: 1, reward: "5 Coins" },
  { title: "10 Minute Meditation in 1 Day", category: 'mental', days: 1, reward: "5 Coins" },
  { title: "30 Minute Meditation in 1 Day", category: 'mental', days: 1, reward: "10 Coins" },
  { title: "1 Hour Meditation in 1 Day", category: 'mental', days: 1, reward: "15 Coins" },
  { title: "Cold Shower in 1 Day", category: 'mental', days: 1, reward: "5 Coins" },
  { title: "1 Hour Digital Detox in 1 Day", category: 'mental', days: 1, reward: "10 Coins" },
  { title: "3 Hour Digital Detox in 1 Day", category: 'mental', days: 1, reward: "15 Coins" },
  { title: "9 Hour (Full Day) Digital Detox in 1 Day", category: 'mental', days: 1, reward: "20 Coins" },
  { title: "Learn 1 New Vocab Word in 1 Day", category: 'mental', days: 1, reward: "5 Coins" },
  { title: "Learn 10 New Vocab Words Over 7 Days", category: 'mental', days: 7, reward: "20 Coins" },
  { title: "Watch Educational Video", category: 'mental', days: 1, reward: "5 Coins" },
  { title: "Write a Short Story in 1 Day", category: 'mental', days: 1, reward: "10 Coins" },
  { title: "Write a Haiku in 1 Day", category: 'mental', days: 1, reward: "10 Coins" },
  { title: "Write a Poem in 1 Day", category: 'mental', days: 1, reward: "10 Coins" },
  { title: "Write a Song in 1 Day", category: 'mental', days: 1, reward: "10 Coins" },
  { title: "Write a Rap Song in 1 Day", category: 'mental', days: 1, reward: "10 Coins" },
  { title: "Write a Letter to Future Self in 1 Day", category: 'mental', days: 1, reward: "10 Coins" },
  { title: "Create a Full Time-Capsule Over 3 Days", category: 'mental', days: 3, reward: "20 Coins" },

  // Personal
  { title: "Learn One New Short-Term Thing Over 7 Days", category: 'personal', days: 7, reward: "20 Coins" },
  { title: "Practice a New Instrument 7 Days Straight", category: 'personal', days: 7, reward: "30 Coins" },
  { title: "Work on a Passion Project for 30 Minutes in 1 Day", category: 'personal', days: 1, reward: "5 Coins" },
  { title: "Work on a Passion Project 7 Days Straight", category: 'personal', days: 7, reward: "30 Coins" },
  { title: "Build a Morning Routine Over 7 Days", category: 'personal', days: 7, reward: "20 Coins" },
  { title: "Build a Night Routine Over 7 Days", category: 'personal', days: 7, reward: "20 Coins" },
  { title: "Clean Your Room in 1 Day", category: 'personal', days: 1, reward: "10 Coins" },
  { title: "Clean Your Desk in 1 Day", category: 'personal', days: 1, reward: "5 Coins" },
  { title: "Create a Budget in 1 Day", category: 'personal', days: 1, reward: "10 Coins" },
  { title: "Fix Something Broken in 1 Day", category: 'personal', days: 1, reward: "10 Coins" },
  { title: "Buy Something That Was Broken in 1 Day", category: 'personal', days: 1, reward: "10 Coins" },
  { title: "Cook a New Recipe in 1 Day", category: 'personal', days: 1, reward: "10 Coins" },

  // Relationships/Friendships
  { title: "Send a Text You've Been Avoiding in 1 Day", category: 'relationships', days: 1, reward: "10 Coins" },
  { title: "Invite Someone to Hangout in 1 Day", category: 'relationships', days: 1, reward: "10 Coins" },
  { title: "Write & Send a Thank-You Note in 1 Day", category: 'relationships', days: 1, reward: "10 Coins" },
  { title: "Share Something You've Created in 1 Day", category: 'relationships', days: 1, reward: "10 Coins" },
  { title: "Random Act of Kindness in 1 Day", category: 'relationships', days: 1, reward: "10 Coins" },
  { title: "Attend a Social Event in 1 Day", category: 'relationships', days: 1, reward: "15 Coins" },
  { title: "Check in on a Friend Over 1 Day", category: 'relationships', days: 1, reward: "15 Coins" },
  { title: "Check in on a Family Member in 1 Day", category: 'relationships', days: 1, reward: "15 Coins" },
  { title: "Have a Deep Conversation in 1 Day", category: 'relationships', days: 1, reward: "15 Coins" },
  { title: "Connect 2 Friends Together in 1 Day", category: 'relationships', days: 1, reward: "15 Coins" },
  { title: "Join a Club Over 7 Days", category: 'relationships', days: 7, reward: "20 Coins" },
  { title: "Make a New Friend Over 7 Days", category: 'relationships', days: 7, reward: "20 Coins" },
  { title: "Ask a Curious Question in Conversation in 1 Day", category: 'relationships', days: 1, reward: "10 Coins" },
  { title: "Compliment 1 Person Genuinely in 1 Day", category: 'relationships', days: 1, reward: "10 Coins" },
  { title: "Compliment 2-10 People Genuinely in 1 Day", category: 'relationships', days: 1, reward: "20 Coins" },
];

export default CHALLENGE_GOALS;
