export interface WrittenPrompt {
	text: string;
}

export interface TriviaQuestion {
	text: string;
	answers: string[];
	correctIndex: number;
}

export const PROMPTS: WrittenPrompt[] = [
	{ text: "Write a Fear: Why It's Irrational" },
	{ text: 'Write Something that makes you Happy, and Why' },
	{ text: "Write 1 Thing You're Grateful for" },
	{ text: "Write 3 Things You're Grateful for" },
	{ text: 'Write 1 Word to Describe Yourself' },
	{ text: '1 Word of How You Feel' },
	{ text: 'Write 3 Ideas' },
	{ text: 'Write 5 Ideas' },
	{ text: 'Write a Short Reflection' },
	{ text: 'Describe your perfect 30-minute break' },
	{ text: 'What small habit would improve your day?' },
	{ text: 'Name one thing you can delegate this week' },
	{ text: 'What made you smile today?' },
	{ text: 'Write one quick goal for tomorrow' },
	{ text: 'Write about a time you handled stress well' },
	{ text: 'What is one learning from today?' },
	{ text: 'Write a short plan to avoid a common distraction' },
	{ text: 'Name a book you want to start this year' },
	{ text: 'Describe a tiny habit you can do before breakfast' },
	{ text: 'What are three sounds you like right now?' },
	{ text: 'Write one thing you can remove from your to-do list' },
	{ text: 'What skill would you like to improve slightly this month?' },
	{ text: 'Write a short note to your future self' },
	{ text: 'Name one healthy food you enjoy and why' },
	{ text: 'Write about a recent small win' },
	{ text: 'What is one small act of kindness you can do?' },
	{ text: 'Describe your favorite place to relax' },
	{ text: 'What habit drains your energy the most?' },
	{ text: 'Write one thing you learned from a mistake' },
	{ text: 'What would make your evening more restful?' },
	{ text: 'Write a one-sentence intention for tomorrow' },
	{ text: 'Name a short podcast or song to listen to tomorrow' },
	{ text: 'Write about one thing you can simplify right now' },
	{ text: 'What small creative task could you do in 10 minutes?' },
	{ text: 'Describe your ideal morning routine' },
	{ text: "What's a compliment you received recently?" },
	{ text: 'Write about a challenge you overcame' },
	{ text: 'What does success look like to you this week?' },
	{ text: "Name three people you're grateful for and why" },
	{ text: 'Write about a hobby you enjoy' },
	{ text: "What's one way you can be kinder to yourself?" },
	{ text: 'Describe a place that brings you peace' },
	{ text: "What's a skill you'd like to learn?" },
	{ text: 'Write about your proudest moment' },
	{ text: 'What makes you feel alive?' },
	{ text: 'Describe your ideal weekend' },
	{ text: "What's something you're looking forward to?" },
	{ text: 'Write about a time you felt truly happy' },
	{ text: "What's one thing you'd tell your younger self?" },
	{ text: 'Describe a conversation that inspired you' },
	{ text: 'What does self-care mean to you?' },
	{ text: "Write about a goal and how you'll achieve it" },
	{ text: "What's something you've been putting off?" },
	{ text: 'Describe your favorite meal and why' },
	{ text: 'What brings out your best self?' },
	{ text: 'Write about a person who inspires you' },
	{ text: "What's one small change you'd like to make?" },
	{ text: 'Describe a moment of pure joy' },
	{ text: 'What does balance mean in your life?' },
	{ text: 'Write about your dream vacation' },
	{ text: "What's something you're proud of today?" },
	{ text: 'Describe a book or movie that changed you' },
	{ text: 'What would you do with an extra hour today?' },
	{ text: 'Write about a time you felt courageous' },
	{ text: "What's your favorite thing about yourself?" },
	{ text: 'Describe a meaningful relationship' },
	{ text: 'What does happiness look like?' },
	{ text: 'Write about your ideal life in 5 years' },
	{ text: "What's something you can celebrate today?" },
	{ text: "Describe a skill you've mastered" },
	{ text: 'What brings you peace?' },
	{ text: 'Write about a time you felt strong' },
	{ text: "What's your biggest dream?" },
	{ text: 'Describe a moment of clarity you had' },
	{ text: 'What does love mean to you?' },
	{ text: 'Write about someone who helped you grow' },
	{ text: "What's one word to describe your year?" },
	{ text: 'Describe your perfect day' },
	{ text: 'What makes you feel grateful?' },
	{ text: 'Write about a risk you took' },
	{ text: "What's something you're excited about?" },
	{ text: 'Describe a time you helped someone' },
	{ text: 'What does home mean to you?' },
	{ text: 'Write about your greatest strength' },
	{ text: "What's a quality you admire in others?" },
	{ text: 'Describe a place that makes you happy' },
	{ text: 'What does growth mean to you?' },
	{ text: 'Write about a time you laughed hard' },
	{ text: "What's something you want to learn?" },
	{ text: 'Describe your favorite memory' },
	{ text: 'What brings you joy?' },
	{ text: 'Write about a time you felt proud' },
	{ text: "What's your definition of success?" },
	{ text: 'Describe a moment of peace' },
	{ text: 'What does family mean to you?' },
	{ text: 'Write about something beautiful you noticed' },
	{ text: "What's one thing you want to improve?" },
	{ text: 'Describe your ideal work environment' },
	{ text: 'Write about a time you felt inspired' },
	{ text: "What's your greatest accomplishment?" },
	{ text: 'What does freedom mean to you?' },
	{ text: 'Write about a place you want to visit' },
	{ text: "What's a habit that's changed your life?" },
	{ text: 'Describe a moment of surprise' },
	{ text: 'What brings you comfort?' },
	{ text: 'Write about your biggest challenge' },
	{ text: 'What does integrity mean?' },
	{ text: 'Describe a person you deeply respect' },
	{ text: "What's something you've forgiven someone for?" },
	{ text: 'Write about a time you felt connected' },
	{ text: 'What does generosity look like?' },
	{ text: 'Describe your biggest breakthrough' },
	{ text: 'What would you change about the world?' },
	{ text: 'Write about a moment of vulnerability' },
	{ text: "What's your favorite way to relax?" },
	{ text: 'Describe what beauty means to you' },
	{ text: "What's one thing you've never done?" },
	{ text: 'Write about a time you stood up for yourself' },
	{ text: 'What does trust mean to you?' },
	{ text: 'Describe a tradition you love' },
	{ text: "What's something you want to let go of?" },
	{ text: 'Write about a time you felt powerful' },
	{ text: 'What does adventure mean?' },
	{ text: 'Describe your ideal support system' },
	{ text: "What's a skill you wish you had?" },
	{ text: 'Write about a time you felt accepted' },
	{ text: 'What does creativity mean?' },
	{ text: 'Describe a moment of stillness' },
	{ text: "What's something you're protecting?" },
	{ text: 'Write about a time you felt free' },
	{ text: 'What does humility look like?' },
	{ text: 'Describe your biggest fear' },
	{ text: "What's one thing you want to experience?" },
	{ text: 'Write about a moment of clarity' },
	{ text: 'What does resilience mean to you?' },
	{ text: 'Describe something you admire in nature' },
	{ text: "What's something you want to try?" },
	{ text: 'Write about a time you felt understood' },
	{ text: 'What does authenticity mean?' },
	{ text: 'Describe your perfect moment' },
	{ text: "What's one change you want to make?" },
	{ text: 'Write about a time you felt grateful' },
	{ text: 'What does hope look like?' },
	{ text: 'Describe what makes a good friend' },
	{ text: "What's something you're working towards?" },
	{ text: 'Write about a time you felt brave' },
	{ text: 'What does peace look like?' },
	{ text: 'Describe a moment that taught you something' },
];

export const TRIVIA: TriviaQuestion[] = [
	{ text: 'Which planet is known as the Red Planet?', answers: ['Mars', 'Venus', 'Jupiter', 'Mercury'], correctIndex: 0 },
	{ text: 'What is the capital of France?', answers: ['Paris', 'Lyon', 'Marseille', 'Nice'], correctIndex: 0 },
	{ text: 'How many minutes are in an hour?', answers: ['60', '50', '45', '30'], correctIndex: 0 },
	{ text: 'Which animal is the fastest land animal?', answers: ['Cheetah', 'Lion', 'Leopard', 'Tiger'], correctIndex: 0 },
	{ text: 'What color do you get by mixing red and blue?', answers: ['Purple', 'Orange', 'Green', 'Brown'], correctIndex: 0 },
	{ text: 'How many continents are there?', answers: ['7', '6', '5', '8'], correctIndex: 0 },
	{ text: 'What currency is used in Japan?', answers: ['Yen', 'Won', 'Dollar', 'Yuan'], correctIndex: 0 },
	{ text: 'Which gas do plants absorb?', answers: ['Carbon Dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen'], correctIndex: 0 },
	{ text: 'What is H2O commonly called?', answers: ['Water', 'Hydrogen', 'Oxygen', 'Steam'], correctIndex: 0 },
	{ text: 'Who painted the Mona Lisa?', answers: ['Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Donatello'], correctIndex: 0 },
	{ text: 'How many sides does a hexagon have?', answers: ['6', '5', '7', '8'], correctIndex: 0 },
	{ text: 'What is the largest ocean?', answers: ['Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'], correctIndex: 0 },
	{ text: 'Which country is known as the Land of the Rising Sun?', answers: ['Japan', 'China', 'South Korea', 'Thailand'], correctIndex: 0 },
	{ text: 'How many strings does a violin have?', answers: ['4', '6', '5', '7'], correctIndex: 0 },
	{ text: 'What is the smallest prime number?', answers: ['2', '3', '5', '7'], correctIndex: 0 },
	{ text: 'Which element has the symbol Au?', answers: ['Gold', 'Silver', 'Copper', 'Platinum'], correctIndex: 0 },
	{ text: 'What is the capital of Italy?', answers: ['Rome', 'Milan', 'Venice', 'Florence'], correctIndex: 0 },
	{ text: 'How many legs does an octopus have?', answers: ['8', '6', '10', '12'], correctIndex: 0 },
	{ text: 'What year did the Titanic sink?', answers: ['1912', '1905', '1915', '1920'], correctIndex: 0 },
	{ text: 'Which planet is closest to the Sun?', answers: ['Mercury', 'Venus', 'Earth', 'Mars'], correctIndex: 0 },
	{ text: 'What is the capital of Germany?', answers: ['Berlin', 'Munich', 'Hamburg', 'Frankfurt'], correctIndex: 0 },
	{ text: 'How many bones does an adult human have?', answers: ['206', '200', '210', '250'], correctIndex: 0 },
	{ text: 'Which mountain is the tallest in the world?', answers: ['Mount Everest', 'K2', 'Kangchenjunga', 'Lhotse'], correctIndex: 0 },
	{ text: 'What is the capital of Spain?', answers: ['Madrid', 'Barcelona', 'Valencia', 'Seville'], correctIndex: 0 },
	{ text: 'How many chambers does a human heart have?', answers: ['4', '3', '2', '5'], correctIndex: 0 },
	{ text: 'Which river is the longest in the world?', answers: ['Nile River', 'Amazon River', 'Yangtze River', 'Mississippi River'], correctIndex: 0 },
	{ text: 'What is the chemical formula for salt?', answers: ['NaCl', 'KCl', 'CaCl2', 'MgCl2'], correctIndex: 0 },
	{ text: 'How many planets are in our solar system?', answers: ['8', '9', '7', '6'], correctIndex: 0 },
	{ text: "Which gas makes up most of Earth's atmosphere?", answers: ['Nitrogen', 'Oxygen', 'Carbon Dioxide', 'Argon'], correctIndex: 0 },
	{ text: 'What is the capital of Japan?', answers: ['Tokyo', 'Kyoto', 'Osaka', 'Nagoya'], correctIndex: 0 },
	{ text: 'How many colors are in a rainbow?', answers: ['7', '6', '8', '5'], correctIndex: 0 },
	{ text: 'Which Shakespeare play features Romeo?', answers: ['Romeo and Juliet', 'Hamlet', 'Macbeth', 'Othello'], correctIndex: 0 },
	{ text: 'What is the capital of Australia?', answers: ['Canberra', 'Sydney', 'Melbourne', 'Brisbane'], correctIndex: 0 },
	{ text: 'How many degrees are in a right angle?', answers: ['90', '180', '45', '60'], correctIndex: 0 },
	{ text: 'Which element is liquid at room temperature?', answers: ['Mercury', 'Lead', 'Gallium', 'Bromine'], correctIndex: 0 },
	{ text: 'What is the capital of Canada?', answers: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'], correctIndex: 0 },
	{ text: 'How many strings does a guitar have?', answers: ['6', '5', '7', '8'], correctIndex: 0 },
	{ text: 'Which Disney movie features Elsa?', answers: ['Frozen', 'Moana', 'Tangled', 'Brave'], correctIndex: 0 },
	{ text: 'What is the capital of Brazil?', answers: ['Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador'], correctIndex: 0 },
	{ text: 'How many mm are in a cm?', answers: ['10', '100', '5', '20'], correctIndex: 0 },
	{ text: 'Which metal is magnetic?', answers: ['Iron', 'Copper', 'Aluminum', 'Gold'], correctIndex: 0 },
	{ text: 'What is the capital of South Africa?', answers: ['Pretoria', 'Cape Town', 'Johannesburg', 'Durban'], correctIndex: 0 },
	{ text: 'How many seconds are in 5 minutes?', answers: ['300', '250', '200', '150'], correctIndex: 0 },
	{ text: 'Who wrote Pride and Prejudice?', answers: ['Jane Austen', 'Charlotte Brontë', 'Emily Brontë', 'Mary Shelley'], correctIndex: 0 },
	{ text: 'What is the capital of Mexico?', answers: ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla'], correctIndex: 0 },
	{ text: 'How many sides does a square have?', answers: ['4', '3', '5', '6'], correctIndex: 0 },
	{ text: 'Which planet has the most moons?', answers: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'], correctIndex: 0 },
	{ text: 'What is the capital of Egypt?', answers: ['Cairo', 'Alexandria', 'Giza', 'Luxor'], correctIndex: 0 },
	{ text: 'How many inches are in a foot?', answers: ['12', '10', '8', '14'], correctIndex: 0 },
	{ text: 'Who invented the lightbulb?', answers: ['Thomas Edison', 'Nikola Tesla', 'Alexander Graham Bell', 'George Westinghouse'], correctIndex: 0 },
	{ text: 'What is the capital of India?', answers: ['New Delhi', 'Mumbai', 'Bangalore', 'Chennai'], correctIndex: 0 },
	{ text: 'How many grams are in a kilogram?', answers: ['1000', '100', '500', '2000'], correctIndex: 0 },
	{ text: 'Which fruit is known for helping with vision?', answers: ['Carrot', 'Apple', 'Banana', 'Orange'], correctIndex: 0 },
	{ text: 'What is the capital of Russia?', answers: ['Moscow', 'St. Petersburg', 'Kazan', 'Sochi'], correctIndex: 0 },
	{ text: 'How many days are in February in a leap year?', answers: ['29', '28', '30', '27'], correctIndex: 0 },
	{ text: 'Who wrote Hamlet?', answers: ['William Shakespeare', 'Christopher Marlowe', 'Ben Jonson', 'John Milton'], correctIndex: 0 },
	{ text: 'What is the capital of Thailand?', answers: ['Bangkok', 'Phuket', 'Chiang Mai', 'Pattaya'], correctIndex: 0 },
	{ text: 'How many fingers do humans have?', answers: ['10', '8', '12', '9'], correctIndex: 0 },
	{ text: 'Which planet is known for its rings?', answers: ['Saturn', 'Jupiter', 'Uranus', 'Neptune'], correctIndex: 0 },
	{ text: 'What is the capital of Greece?', answers: ['Athens', 'Thessaloniki', 'Patras', 'Heraklion'], correctIndex: 0 },
	{ text: 'How many vowels are in the English alphabet?', answers: ['5', '6', '4', '7'], correctIndex: 0 },
	{ text: 'Who painted Starry Night?', answers: ['Vincent van Gogh', 'Pablo Picasso', 'Claude Monet', 'Paul Cézanne'], correctIndex: 0 },
	{ text: 'What is the capital of Sweden?', answers: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala'], correctIndex: 0 },
	{ text: 'How many planets have rings?', answers: ['4', '3', '2', '5'], correctIndex: 0 },
	{ text: 'Which vitamin is found in oranges?', answers: ['Vitamin C', 'Vitamin A', 'Vitamin D', 'Vitamin B12'], correctIndex: 0 },
	{ text: 'What is the capital of Norway?', answers: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger'], correctIndex: 0 },
	{ text: 'How many degrees in a circle?', answers: ['360', '180', '720', '90'], correctIndex: 0 },
	{ text: 'Who wrote The Great Gatsby?', answers: ['F. Scott Fitzgerald', 'Ernest Hemingway', 'John Steinbeck', 'Mark Twain'], correctIndex: 0 },
	{ text: 'What is the capital of Argentina?', answers: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza'], correctIndex: 0 },
	{ text: 'How many moons does Earth have?', answers: ['1', '2', '3', '0'], correctIndex: 0 },
	{ text: 'Which planet is closest to Earth?', answers: ['Venus', 'Mercury', 'Mars', 'Jupiter'], correctIndex: 0 },
	{ text: 'What is the capital of South Korea?', answers: ['Seoul', 'Busan', 'Incheon', 'Daegu'], correctIndex: 0 },
	{ text: 'How many chromosomes do humans have?', answers: ['46', '44', '48', '42'], correctIndex: 0 },
	{ text: 'Who composed The Four Seasons?', answers: ['Antonio Vivaldi', 'Johann Sebastian Bach', 'Mozart', 'Beethoven'], correctIndex: 0 },
	{ text: 'What is the capital of Poland?', answers: ['Warsaw', 'Kraków', 'Gdańsk', 'Wrocław'], correctIndex: 0 },
	{ text: 'How many layers does the Earth have?', answers: ['3', '4', '5', '2'], correctIndex: 0 },
	{ text: 'Which animal can change colors?', answers: ['Chameleon', 'Gecko', 'Iguana', 'Frog'], correctIndex: 0 },
	{ text: 'What is the capital of Portugal?', answers: ['Lisbon', 'Porto', 'Braga', 'Coimbra'], correctIndex: 0 },
	{ text: 'How many ounces are in a pound?', answers: ['16', '14', '12', '18'], correctIndex: 0 },
	{ text: 'Who invented the telephone?', answers: ['Alexander Graham Bell', 'Thomas Edison', 'Nikola Tesla', 'Samuel Morse'], correctIndex: 0 },
	{ text: 'What is the capital of Netherlands?', answers: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht'], correctIndex: 0 },
	{ text: 'How many days are in a year?', answers: ['365', '360', '366', '350'], correctIndex: 0 },
	{ text: 'Which ocean is the smallest?', answers: ['Arctic Ocean', 'Indian Ocean', 'Southern Ocean', 'Atlantic Ocean'], correctIndex: 0 },
	{ text: 'What is the capital of Belgium?', answers: ['Brussels', 'Antwerp', 'Ghent', 'Bruges'], correctIndex: 0 },
	{ text: 'How many eyelids does a human have on each eye?', answers: ['2', '1', '3', '4'], correctIndex: 0 },
	{ text: 'Who wrote 1984?', answers: ['George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'Kurt Vonnegut'], correctIndex: 0 },
	{ text: 'What is the capital of Switzerland?', answers: ['Bern', 'Zurich', 'Geneva', 'Basel'], correctIndex: 0 },
	{ text: 'How many millimeters are in an inch?', answers: ['25.4', '20', '30', '22'], correctIndex: 0 },
	{ text: 'Which gas do animals breathe to survive?', answers: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Helium'], correctIndex: 0 },
	{ text: 'What is the capital of Turkey?', answers: ['Ankara', 'Istanbul', 'Izmir', 'Antalya'], correctIndex: 0 },
	{ text: 'How many teeth does an adult human have?', answers: ['32', '28', '30', '34'], correctIndex: 0 },
	{ text: 'Who painted The Persistence of Memory?', answers: ['Salvador Dalí', 'Joan Miró', 'Picasso', 'René Magritte'], correctIndex: 0 },
	{ text: 'What is the capital of China?', answers: ['Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen'], correctIndex: 0 },
	{ text: 'How many sides does a pentagon have?', answers: ['5', '6', '7', '8'], correctIndex: 0 },
	{ text: 'Which mineral is diamond made of?', answers: ['Carbon', 'Silicon', 'Quartz', 'Graphite'], correctIndex: 0 },
];

export const ADVICE: string[] = ['Start your day with a clear intention.', 'Small steps lead to big changes.', 'Focus on what you can control today.', 'Break large goals into tiny habits.', 'Progress over perfection.', 'Rest is part of productivity.', 'Be kind to yourself today.', 'One day at a time.', 'You are stronger than you think.', 'Celebrate small wins.', 'Consistency beats intensity.', 'Today is a fresh start.'];

export const QUOTES: string[] = [
	'The only way to do great work is to love what you do. - Steve Jobs',
	'Success is not final, failure is not fatal. - Winston Churchill',
	"You miss 100% of the shots you don't take. - Wayne Gretzky",
	'The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb',
	'It does not matter how slowly you go as long as you do not stop. - Confucius',
	'Everything you want is on the other side of fear. - George Addair',
	'You are never too old to set another goal or to dream a new dream. - C.S. Lewis',
	'The only impossible journey is the one you never begin. - Tony Robbins',
	'What we think, we become. - Buddha',
	'Act as if what you do makes a difference. It does. - William James',
];

export default PROMPTS;
