// Suggested Goals for Daily Habits and To-Do Items
// Used in surveys for quick goal suggestions

export interface SuggestedHabitGoal {
	title: string;
	category: 'Physical' | 'Mental' | 'Personal' | 'Social' | 'Creative' | 'Wellness';
	timesPerWeek?: number;
	importance?: 'Default' | 'Important' | 'Important+';
}

export interface SuggestedTodoGoal {
	title: string;
	category: 'Physical' | 'Mental' | 'Personal' | 'Social' | 'Creative' | 'Wellness' | 'Learning';
	dueDate?: number; // days from today
	coins: number;
	shards?: number;
	description?: string;
}

// 100+ Habit Goals (evenly distributed across categories)
export const SUGGESTED_HABIT_GOALS: SuggestedHabitGoal[] = [
	// Physical (18 items)
	{ title: 'Do 20 Push-ups', category: 'Physical', importance: 'Default' },
	{ title: 'Do 50 Push-ups', category: 'Physical', importance: 'Important' },
	{ title: 'Run 1 Mile', category: 'Physical', importance: 'Default' },
	{ title: 'Run 3 Miles', category: 'Physical', importance: 'Important' },
	{ title: 'Do 10 Pull-ups', category: 'Physical', importance: 'Important' },
	{ title: 'Do 30 Squats', category: 'Physical', importance: 'Default' },
	{ title: 'Do 100 Squats', category: 'Physical', importance: 'Important' },
	{ title: 'Go for a Walk', category: 'Physical', importance: 'Default', timesPerWeek: 4 },
	{ title: 'Swim 5 Laps', category: 'Physical', importance: 'Important' },
	{ title: 'Stretch for 10 Minutes', category: 'Physical', importance: 'Default' },
	{ title: 'Do Yoga for 30 Minutes', category: 'Physical', importance: 'Default' },
	{ title: 'Go Biking', category: 'Physical', importance: 'Default' },
	{ title: 'Jump Rope for 10 Minutes', category: 'Physical', importance: 'Default' },
	{ title: 'Do Planks (30 seconds)', category: 'Physical', importance: 'Default' },
	{ title: 'Do Burpees (20 reps)', category: 'Physical', importance: 'Important' },
	{ title: 'Ride Stationary Bike', category: 'Physical', importance: 'Default' },
	{ title: 'Do Mountain Climbers', category: 'Physical', importance: 'Default' },
	{ title: 'Go Hiking', category: 'Physical', importance: 'Important' },

	// Mental (20 items)
	{ title: '10 Minute Meditation', category: 'Mental', importance: 'Default' },
	{ title: '30 Minute Meditation', category: 'Mental', importance: 'Important' },
	{ title: 'Read 10 Pages', category: 'Mental', importance: 'Default' },
	{ title: 'Read 30 Pages', category: 'Mental', importance: 'Important' },
	{ title: 'Do Deep Breathing Exercise', category: 'Mental', importance: 'Default' },
	{ title: 'Take a Cold Shower', category: 'Mental', importance: 'Important' },
	{ title: '1 Hour Digital Detox', category: 'Mental', importance: 'Default' },
	{ title: '3 Hour Digital Detox', category: 'Mental', importance: 'Important' },
	{ title: 'Learn 1 New Vocabulary Word', category: 'Mental', importance: 'Default' },
	{ title: 'Journaling Session', category: 'Mental', importance: 'Default' },
	{ title: 'Brain Teaser or Puzzle', category: 'Mental', importance: 'Default' },
	{ title: 'Listen to Podcast (30 min)', category: 'Mental', importance: 'Default' },
	{ title: 'Watch Educational Video', category: 'Mental', importance: 'Default' },
	{ title: 'Practice Mindfulness', category: 'Mental', importance: 'Default' },
	{ title: 'Solve a Sudoku', category: 'Mental', importance: 'Default' },
	{ title: 'Do Crossword Puzzle', category: 'Mental', importance: 'Default' },
	{ title: 'Write Gratitude List', category: 'Mental', importance: 'Default' },
	{ title: 'Practice Visualization', category: 'Mental', importance: 'Default' },
	{ title: 'Affirmation Recitation', category: 'Mental', importance: 'Default' },
	{ title: 'Philosophy Reading', category: 'Mental', importance: 'Important' },

	// Personal (21 items)
	{ title: 'Clean Your Room', category: 'Personal', importance: 'Default' },
	{ title: 'Organize Your Desk', category: 'Personal', importance: 'Default' },
	{ title: 'Do Laundry', category: 'Personal', importance: 'Default' },
	{ title: 'Meal Prep for Week', category: 'Personal', importance: 'Important' },
	{ title: 'Cook a New Recipe', category: 'Personal', importance: 'Default' },
	{ title: 'Work on Passion Project (30 min)', category: 'Personal', importance: 'Important' },
	{ title: 'Learn New Skill (30 min)', category: 'Personal', importance: 'Default' },
	{ title: 'Practice Instrument (30 min)', category: 'Personal', importance: 'Important' },
	{ title: 'Organize Financial Documents', category: 'Personal', importance: 'Important' },
	{ title: 'Update Personal Budget', category: 'Personal', importance: 'Important' },
	{ title: 'Fix Something Around House', category: 'Personal', importance: 'Default' },
	{ title: 'Plant Watering/Gardening', category: 'Personal', importance: 'Default' },
	{ title: 'Wash Your Car', category: 'Personal', importance: 'Default' },
	{ title: 'Home Maintenance Task', category: 'Personal', importance: 'Default' },
	{ title: 'Organize Photos', category: 'Personal', importance: 'Default' },
	{ title: 'Review Goals for Week', category: 'Personal', importance: 'Important' },
	{ title: 'Evening Reflection', category: 'Personal', importance: 'Default' },
	{ title: 'Plan Next Day', category: 'Personal', importance: 'Default' },
	{ title: 'Take Vitamins/Medications', category: 'Personal', importance: 'Default' },
	{ title: 'Skincare Routine', category: 'Personal', importance: 'Default' },
	{ title: 'Nail Care', category: 'Personal', importance: 'Default' },

	// Social (20 items)
	{ title: 'Text a Friend', category: 'Social', importance: 'Default' },
	{ title: 'Call Family Member', category: 'Social', importance: 'Important' },
	{ title: 'Send Thank You Note', category: 'Social', importance: 'Important' },
	{ title: 'Make Plans with Friend', category: 'Social', importance: 'Default' },
	{ title: 'Compliment Someone', category: 'Social', importance: 'Default' },
	{ title: 'Share Something You Created', category: 'Social', importance: 'Important' },
	{ title: 'Random Act of Kindness', category: 'Social', importance: 'Important' },
	{ title: 'Listen to Friend Without Advice', category: 'Social', importance: 'Default' },
	{ title: 'Ask Someone About Themselves', category: 'Social', importance: 'Default' },
	{ title: 'Attend Social Event', category: 'Social', importance: 'Important' },
	{ title: 'Volunteer', category: 'Social', importance: 'Important' },
	{ title: 'Join Online Community', category: 'Social', importance: 'Default' },
	{ title: 'Video Call Someone', category: 'Social', importance: 'Default' },
	{ title: 'Attend Class or Workshop', category: 'Social', importance: 'Important' },
	{ title: 'Network with Colleague', category: 'Social', importance: 'Important' },
	{ title: 'Join Study Group', category: 'Social', importance: 'Default' },
	{ title: 'Host a Gathering', category: 'Social', importance: 'Important' },
	{ title: 'Mentor Someone', category: 'Social', importance: 'Important' },
	{ title: 'Check on Elderly Friend', category: 'Social', importance: 'Important' },
	{ title: 'Apologize if Needed', category: 'Social', importance: 'Important' },

	// Creative (20 items)
	{ title: 'Write Short Story', category: 'Creative', importance: 'Default' },
	{ title: 'Create Digital Art', category: 'Creative', importance: 'Default' },
	{ title: 'Draw or Sketch', category: 'Creative', importance: 'Default' },
	{ title: 'Write a Poem', category: 'Creative', importance: 'Default' },
	{ title: 'Compose Music', category: 'Creative', importance: 'Important' },
	{ title: 'Photography Session', category: 'Creative', importance: 'Default' },
	{ title: 'Video Creation', category: 'Creative', importance: 'Important' },
	{ title: 'Write Song Lyrics', category: 'Creative', importance: 'Default' },
	{ title: 'Crafting Project', category: 'Creative', importance: 'Default' },
	{ title: 'Poetry Writing', category: 'Creative', importance: 'Default' },
	{ title: 'Creative Writing Prompt', category: 'Creative', importance: 'Default' },
	{ title: 'Design Something New', category: 'Creative', importance: 'Default' },
	{ title: 'DIY Project', category: 'Creative', importance: 'Default' },
	{ title: 'Remix or Cover Song', category: 'Creative', importance: 'Important' },
	{ title: 'Create Mood Board', category: 'Creative', importance: 'Default' },
	{ title: 'Write Haiku', category: 'Creative', importance: 'Default' },
	{ title: 'Paint or Watercolor', category: 'Creative', importance: 'Default' },
	{ title: 'Sculpting or 3D Creation', category: 'Creative', importance: 'Default' },
	{ title: 'Collage Making', category: 'Creative', importance: 'Default' },
	{ title: 'Journaling with Art', category: 'Creative', importance: 'Default' },

	// Wellness (21 items)
	{ title: 'Drink 8 Glasses of Water', category: 'Wellness', importance: 'Default' },
	{ title: 'Eat 5 Servings of Vegetables', category: 'Wellness', importance: 'Important' },
	{ title: 'Sleep 8+ Hours', category: 'Wellness', importance: 'Important' },
	{ title: 'Wake Up Early', category: 'Wellness', importance: 'Important' },
	{ title: 'Take Vitamins', category: 'Wellness', importance: 'Default' },
	{ title: 'Limit Sugar Intake', category: 'Wellness', importance: 'Default' },
	{ title: 'No Junk Food Today', category: 'Wellness', importance: 'Important' },
	{ title: 'Eat Healthy Breakfast', category: 'Wellness', importance: 'Important' },
	{ title: 'Eat Balanced Dinner', category: 'Wellness', importance: 'Default' },
	{ title: 'Stretch Before Bed', category: 'Wellness', importance: 'Default' },
	{ title: 'No Caffeine After 2pm', category: 'Wellness', importance: 'Default' },
	{ title: 'Limit Screen Time (2 hours)', category: 'Wellness', importance: 'Important' },
	{ title: 'Practice Sun Exposure', category: 'Wellness', importance: 'Default' },
	{ title: 'Check In on Mental Health', category: 'Wellness', importance: 'Important' },
	{ title: 'Practice Self-Care', category: 'Wellness', importance: 'Default' },
	{ title: 'Bath or Spa Time', category: 'Wellness', importance: 'Default' },
	{ title: 'Moisturize Skin', category: 'Wellness', importance: 'Default' },
	{ title: 'Floss Teeth', category: 'Wellness', importance: 'Default' },
	{ title: 'Brush Teeth Twice', category: 'Wellness', importance: 'Default' },
	{ title: 'Relax with Tea', category: 'Wellness', importance: 'Default' },
	{ title: 'Oil Skin Massage', category: 'Wellness', importance: 'Default' },
];

// 100+ To-Do Goals with rewards
export const SUGGESTED_TODO_GOALS: SuggestedTodoGoal[] = [
	// Physical (16 items)
	{ title: 'Do 50 Pushups Over 1 Day', category: 'Physical', dueDate: 1, coins: 5 },
	{ title: 'Do 100 Pushups Over 2 Days', category: 'Physical', dueDate: 2, coins: 10 },
	{ title: 'Do 150 Pushups Over 3 Days', category: 'Physical', dueDate: 3, coins: 15 },
	{ title: 'Do 10 Pull Ups Over 1 Day', category: 'Physical', dueDate: 1, coins: 7 },
	{ title: 'Do 20 Pull Ups Over 2 Days', category: 'Physical', dueDate: 2, coins: 12 },
	{ title: 'Do 100 Squats Over 1 Day', category: 'Physical', dueDate: 1, coins: 5 },
	{ title: 'Do 200 Squats Over 2 Days', category: 'Physical', dueDate: 2, coins: 10 },
	{ title: 'Run a Mile in Under 10 Minutes', category: 'Physical', dueDate: 1, coins: 5 },
	{ title: 'Run 5 Miles in 1 Day', category: 'Physical', dueDate: 1, coins: 15 },
	{ title: 'Run 10 Miles in 7 Days', category: 'Physical', dueDate: 7, coins: 20 },
	{ title: 'Swim 10 Laps', category: 'Physical', dueDate: 1, coins: 10 },
	{ title: 'Go Hiking 5 Miles', category: 'Physical', dueDate: 1, coins: 15 },
	{ title: 'Complete Bike Ride 10 Miles', category: 'Physical', dueDate: 1, coins: 12 },
	{ title: 'Join Sports Meetup', category: 'Physical', dueDate: 7, coins: 15 },
	{ title: 'Win a Race', category: 'Physical', dueDate: 7, coins: 20 },
	{ title: '30 Day Fitness Challenge', category: 'Physical', dueDate: 30, coins: 50 },

	// Mental (25 items)
	{ title: 'Wake Up Before 5am', category: 'Mental', dueDate: 1, coins: 5 },
	{ title: 'Wake Up Before 6am Daily (7 days)', category: 'Mental', dueDate: 7, coins: 20 },
	{ title: 'Sleep 9+ Hours Tonight', category: 'Mental', dueDate: 1, coins: 10 },
	{ title: 'Read 10 Pages of a Book', category: 'Mental', dueDate: 1, coins: 5 },
	{ title: 'Read Full Book (7 days)', category: 'Mental', dueDate: 7, coins: 20 },
	{ title: 'Do 100 Deep Breaths', category: 'Mental', dueDate: 1, coins: 5 },
	{ title: '10 Minute Meditation', category: 'Mental', dueDate: 1, coins: 5 },
	{ title: '30 Minute Meditation', category: 'Mental', dueDate: 1, coins: 10 },
	{ title: '1 Hour Meditation', category: 'Mental', dueDate: 1, coins: 15 },
	{ title: 'Cold Shower Challenge', category: 'Mental', dueDate: 1, coins: 5 },
	{ title: '1 Hour Digital Detox', category: 'Mental', dueDate: 1, coins: 10 },
	{ title: '3 Hour Digital Detox', category: 'Mental', dueDate: 1, coins: 15 },
	{ title: 'Full Day Digital Detox (9+ hours)', category: 'Mental', dueDate: 1, coins: 20 },
	{ title: 'Learn 10 New Vocabulary Words', category: 'Mental', dueDate: 7, coins: 20 },
	{ title: 'Watch Educational Video Series', category: 'Mental', dueDate: 3, coins: 10 },
	{ title: 'Write a Short Story', category: 'Mental', dueDate: 1, coins: 10 },
	{ title: 'Write a Haiku', category: 'Mental', dueDate: 1, coins: 10 },
	{ title: 'Write a Full Poem', category: 'Mental', dueDate: 1, coins: 10 },
	{ title: 'Write a Song', category: 'Mental', dueDate: 3, coins: 10 },
	{ title: 'Write Letter to Future Self', category: 'Mental', dueDate: 1, coins: 10 },
	{ title: 'Complete Time Capsule', category: 'Mental', dueDate: 3, coins: 20 },
	{ title: 'Brain Teaser Challenge (5 puzzles)', category: 'Mental', dueDate: 1, coins: 8 },
	{ title: 'Solve Cryptic Crossword', category: 'Mental', dueDate: 2, coins: 10 },
	{ title: 'Read Philosophy Book Chapter', category: 'Mental', dueDate: 2, coins: 10 },
	{ title: 'Attend Lecture or Webinar', category: 'Mental', dueDate: 1, coins: 15 },

	// Personal (25 items)
	{ title: 'Learn One Short-Term Skill', category: 'Personal', dueDate: 7, coins: 20 },
	{ title: 'Practice New Instrument 7 Days', category: 'Personal', dueDate: 7, coins: 30 },
	{ title: 'Work on Passion Project 30 min', category: 'Personal', dueDate: 1, coins: 5 },
	{ title: 'Work on Passion Project 7 Days', category: 'Personal', dueDate: 7, coins: 30 },
	{ title: 'Build Morning Routine (7 days)', category: 'Personal', dueDate: 7, coins: 20 },
	{ title: 'Build Night Routine (7 days)', category: 'Personal', dueDate: 7, coins: 20 },
	{ title: 'Deep Clean Your Room', category: 'Personal', dueDate: 1, coins: 10 },
	{ title: 'Clean Your Desk Thoroughly', category: 'Personal', dueDate: 1, coins: 5 },
	{ title: 'Organize Entire Bedroom', category: 'Personal', dueDate: 3, coins: 15 },
	{ title: 'Create Personal Budget', category: 'Personal', dueDate: 1, coins: 10 },
	{ title: 'Review and Adjust Budget', category: 'Personal', dueDate: 7, coins: 15 },
	{ title: 'Fix Something Broken', category: 'Personal', dueDate: 1, coins: 10 },
	{ title: 'Purchase and Repair Item', category: 'Personal', dueDate: 2, coins: 10 },
	{ title: 'Cook New Recipe', category: 'Personal', dueDate: 1, coins: 10 },
	{ title: 'Master New Cooking Technique', category: 'Personal', dueDate: 3, coins: 15 },
	{ title: 'Plan Meals for Week', category: 'Personal', dueDate: 1, coins: 8 },
	{ title: 'Organize Financial Records', category: 'Personal', dueDate: 2, coins: 12 },
	{ title: 'Update Emergency Fund Plan', category: 'Personal', dueDate: 1, coins: 10 },
	{ title: 'Review Insurance Documents', category: 'Personal', dueDate: 3, coins: 15 },
	{ title: 'Set Up New System/Tool', category: 'Personal', dueDate: 1, coins: 10 },
	{ title: 'Plant a Garden', category: 'Personal', dueDate: 7, coins: 20 },
	{ title: 'Landscaping Project', category: 'Personal', dueDate: 2, coins: 15 },
	{ title: 'Home Maintenance Task', category: 'Personal', dueDate: 1, coins: 10 },
	{ title: 'Paint a Room', category: 'Personal', dueDate: 3, coins: 20 },
	{ title: 'Organize Photo Library', category: 'Personal', dueDate: 2, coins: 10 },

	// Social (18 items)
	{ title: 'Send Text You Were Avoiding', category: 'Social', dueDate: 1, coins: 10 },
	{ title: 'Invite Someone to Hangout', category: 'Social', dueDate: 1, coins: 10 },
	{ title: 'Write & Send Thank You Note', category: 'Social', dueDate: 1, coins: 10 },
	{ title: 'Share Your Creation', category: 'Social', dueDate: 1, coins: 10 },
	{ title: 'Random Act of Kindness', category: 'Social', dueDate: 1, coins: 10 },
	{ title: 'Attend Social Event', category: 'Social', dueDate: 1, coins: 15 },
	{ title: 'Check In on Friend (1 day)', category: 'Social', dueDate: 1, coins: 15 },
	{ title: 'Check In on Family Member', category: 'Social', dueDate: 1, coins: 15 },
	{ title: 'Have Deep Conversation', category: 'Social', dueDate: 1, coins: 15 },
	{ title: 'Connect 2 Friends Together', category: 'Social', dueDate: 1, coins: 15 },
	{ title: 'Join a Club (7 days)', category: 'Social', dueDate: 7, coins: 20 },
	{ title: 'Make a New Friend (7 days)', category: 'Social', dueDate: 7, coins: 20 },
	{ title: 'Ask Curious Question in Conversation', category: 'Social', dueDate: 1, coins: 10 },
	{ title: 'Compliment 1 Person Genuinely', category: 'Social', dueDate: 1, coins: 10 },
	{ title: 'Compliment 5 People Genuinely', category: 'Social', dueDate: 1, coins: 15 },
	{ title: 'Host a Dinner Party', category: 'Social', dueDate: 7, coins: 25 },
	{ title: 'Mentor Someone', category: 'Social', dueDate: 7, coins: 25 },
	{ title: 'Apologize if Needed', category: 'Social', dueDate: 1, coins: 15 },

	// Creative (16 items)
	{ title: 'Create Short Story (1000+ words)', category: 'Creative', dueDate: 3, coins: 15 },
	{ title: 'Create Digital Art Piece', category: 'Creative', dueDate: 2, coins: 10 },
	{ title: 'Draw 5 Sketches', category: 'Creative', dueDate: 1, coins: 8 },
	{ title: 'Write Poetry Collection (5 poems)', category: 'Creative', dueDate: 3, coins: 15 },
	{ title: 'Compose Music Piece', category: 'Creative', dueDate: 7, coins: 25 },
	{ title: 'Photography Portfolio (10+ photos)', category: 'Creative', dueDate: 3, coins: 15 },
	{ title: 'Create Short Video (2+ min)', category: 'Creative', dueDate: 2, coins: 15 },
	{ title: 'Write Song with Lyrics', category: 'Creative', dueDate: 3, coins: 15 },
	{ title: 'Complete Crafting Project', category: 'Creative', dueDate: 2, coins: 10 },
	{ title: 'Design Logo or Graphic', category: 'Creative', dueDate: 1, coins: 12 },
	{ title: 'Paint or Watercolor Art (1 piece)', category: 'Creative', dueDate: 2, coins: 10 },
	{ title: 'Complete DIY Home Project', category: 'Creative', dueDate: 3, coins: 15 },
	{ title: 'Sculpture or 3D Project', category: 'Creative', dueDate: 3, coins: 15 },
	{ title: 'Create Mood Board (50+ items)', category: 'Creative', dueDate: 1, coins: 8 },
	{ title: 'Make Collage Art Piece', category: 'Creative', dueDate: 1, coins: 8 },
	{ title: 'Write Comic Strip or Manga Panel', category: 'Creative', dueDate: 2, coins: 12 },
];
