import { useTheme, type ThemeColors } from '@/context/ThemeProvider';
import { useMemo } from 'react';
import { StyleSheet } from 'react-native';

const fallbackColors: ThemeColors = {
	background: '#FFFFFF',
	primaryBackground: '#FFFFFF',
	secondaryBackground: '#F9FAFB',
	tertiaryBackground: '#F3F4F6',
	fourthBackground: '#E5E7EB',
	card: '#FFFFFF',
	border: '#E5E7EB',
	inputBackground: '#FFFFFF',
	text: '#111827',
	titleText: '#111827',
	headerText: '#111827',
	subheaderText: '#374151',
	secondaryText: '#6B7280',
	tint: '#2563EB',
	success: '#4CAF50',
	warning: '#B45309',
	danger: '#DC2626',
	info: '#1976D2',
	tabIconDefault: '#9CA3AF',
	tabIconSelected: '#2563EB',
	buttonBackground: '#4CAF50',
	buttonText: '#FFFFFF',
	secondaryButton: '#F3F4F6',
	secondaryButtonText: '#374151',
};

export const createSectionStyles = (colors: ThemeColors) => StyleSheet.create({
	container: { flex: 1, backgroundColor: colors.background },
	content: { flex: 1, padding: 16, backgroundColor: colors.background },
	contentArea: { flex: 1 },
	title: { fontSize: 24, fontWeight: 'bold', marginBottom: 20, textAlign: 'center', color: colors.titleText },
	progressContainer: { paddingHorizontal: 16, marginBottom: 8 },
	progressBar: { height: 8, backgroundColor: colors.tertiaryBackground, borderRadius: 4, overflow: 'hidden', marginBottom: 8 },
	progressFill: { height: '100%', backgroundColor: colors.success },
	progressText: { fontSize: 12, textAlign: 'right', color: colors.secondaryText },
	closeButton: { width: 44, height: 44, justifyContent: 'center', alignItems: 'center', marginLeft: 8 },
	closeButtonText: { fontSize: 28, fontWeight: '300', color: colors.secondaryText },
	surveyLabelContainer: { paddingVertical: 12, paddingHorizontal: 16, backgroundColor: colors.secondaryBackground, borderBottomWidth: 1, borderColor: colors.border, alignItems: 'center' },
	surveyLabelText: { fontSize: 18, fontWeight: '700', color: colors.headerText },
	surveyContent: { flex: 1, paddingHorizontal: 16 },
	surveyContentInner: { paddingVertical: 20 },
	listContentContainer: { paddingHorizontal: 12, paddingVertical: 12 },
	question: { fontSize: 17, fontWeight: '700', marginBottom: 10, color: colors.headerText },
	adviceText: { fontSize: 16, lineHeight: 24, color: colors.text, marginBottom: 8 },
	adviceLabel: { fontSize: 13, color: colors.secondaryText, fontStyle: 'italic' },
	bodyText: { color: colors.text },
	helperText: { fontSize: 12, color: colors.secondaryText },
	infoText: { fontSize: 11, color: colors.info, marginTop: 4 },
	lockedText: { fontSize: 11, color: colors.secondaryText, marginTop: 6 },
	factCard: { borderWidth: 1, borderColor: colors.border, borderRadius: 8, backgroundColor: colors.secondaryBackground, padding: 12, marginBottom: 10 },
	factNumber: { fontSize: 11, fontWeight: '800', color: colors.secondaryText, marginBottom: 6, textTransform: 'uppercase' },
	label: { fontSize: 14, fontWeight: '600', color: colors.secondaryText },
	textInputArea: { borderWidth: 1, borderColor: colors.border, borderRadius: 8, padding: 12, minHeight: 100, fontSize: 16, backgroundColor: colors.inputBackground, color: colors.text },
	buttonContainer: { flexDirection: 'row', gap: 10, paddingHorizontal: 16, paddingVertical: 12, paddingBottom: 24, borderTopWidth: 1, borderTopColor: colors.border, backgroundColor: colors.background },
	buttonPrevious: { flex: 1, paddingVertical: 12, backgroundColor: colors.secondaryButton, borderRadius: 8, alignItems: 'center', borderWidth: 1, borderColor: colors.border },
	buttonSmall: { flex: 1, paddingVertical: 12, backgroundColor: colors.secondaryButton, borderRadius: 8, alignItems: 'center', borderWidth: 1, borderColor: colors.border, marginRight: 8 },
	buttonNext: { flex: 1, paddingVertical: 12, backgroundColor: colors.success, borderRadius: 8, alignItems: 'center' },
	buttonDisabled: { backgroundColor: colors.tertiaryBackground, opacity: 0.6 },
	buttonText: { fontSize: 14, fontWeight: '600', color: colors.secondaryButtonText },
	buttonTextPrimary: { fontSize: 14, fontWeight: '600', color: colors.buttonText },
	smallButton: { paddingVertical: 8, paddingHorizontal: 12, backgroundColor: colors.secondaryButton, borderRadius: 8, alignSelf: 'flex-start', marginTop: 8, borderWidth: 1, borderColor: colors.border },
	smallButtonText: { fontSize: 13, fontWeight: '600', color: colors.secondaryButtonText },
	rerollButton: { paddingVertical: 10, paddingHorizontal: 12, backgroundColor: colors.tertiaryBackground, borderRadius: 8, alignSelf: 'flex-start', marginTop: 12, borderWidth: 1, borderColor: colors.border },
	rerollButtonText: { fontSize: 13, fontWeight: '600', color: colors.info },
	miniButton: { minWidth: 42, height: 28, borderRadius: 6, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 8 },
	miniEditButton: { backgroundColor: colors.info },
	miniButtonText: { fontSize: 12, fontWeight: '700', color: colors.buttonText },
	moodGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, justifyContent: 'space-between' },
	moodButton: { width: '30%', minHeight: 78, padding: 10, borderRadius: 8, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.secondaryBackground, alignItems: 'center', justifyContent: 'center', marginBottom: 8 },
	moodSelected: { borderColor: colors.success, backgroundColor: colors.tertiaryBackground },
	moodEmoji: { fontSize: 24, marginBottom: 6 },
	moodLabel: { fontSize: 12, textAlign: 'center', color: colors.text },
	habitRow: { padding: 10, borderRadius: 8, borderWidth: 1, borderColor: colors.border, marginBottom: 7, backgroundColor: colors.secondaryBackground },
	habitImportant: { borderColor: colors.border, backgroundColor: colors.secondaryBackground },
	habitImportantPlus: { borderColor: colors.border, backgroundColor: colors.secondaryBackground },
	habitTitle: { fontSize: 15, fontWeight: '800', color: colors.titleText },
	habitMeta: { fontSize: 11, color: colors.secondaryText, marginTop: 3 },
	challengeRow: { padding: 10, borderRadius: 8, borderWidth: 1, borderColor: colors.info, marginBottom: 7, backgroundColor: colors.tertiaryBackground },
	habitCompleted: { borderColor: colors.success, backgroundColor: colors.tertiaryBackground },
	suggestedScrollView: { maxHeight: 300, borderRadius: 8, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.secondaryBackground },
	suggestedItem: { paddingVertical: 8, paddingHorizontal: 10, borderBottomWidth: 1, borderBottomColor: colors.border, backgroundColor: colors.secondaryBackground },
	todoItem: { padding: 10, borderRadius: 8, borderWidth: 1, borderColor: colors.border, marginBottom: 7, backgroundColor: colors.secondaryBackground },
	todoImportant: { borderColor: colors.border, backgroundColor: colors.secondaryBackground },
	todoImportantPlus: { borderColor: colors.border, backgroundColor: colors.secondaryBackground },
	todoCompleted: { borderColor: colors.success, backgroundColor: colors.tertiaryBackground },
	subGoalRow: { flexDirection: 'row', alignItems: 'center', paddingLeft: 8, paddingVertical: 4 },
	goalMainRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 8 },
	goalTextColumn: { flex: 1, minWidth: 0 },
	goalActionRow: { flexDirection: 'row', alignItems: 'center', gap: 6, flexShrink: 0 },
	goalActionText: { fontSize: 11, fontWeight: '800' },
	metaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginTop: 5, alignItems: 'center' },
	importanceChip: { paddingVertical: 3, paddingHorizontal: 7, borderRadius: 999, backgroundColor: colors.inputBackground, borderWidth: 1 },
	importanceText: { fontSize: 10, fontWeight: '900' },
	categoryChip: { paddingVertical: 3, paddingHorizontal: 7, borderRadius: 999, backgroundColor: colors.tertiaryBackground, borderWidth: 1, borderColor: colors.border },
	categoryChipText: { fontSize: 10, fontWeight: '800', color: colors.secondaryButtonText },
	subtleText: { fontSize: 12, color: colors.secondaryText },
	warningText: { fontSize: 12, color: colors.warning, marginTop: 6, lineHeight: 18 },
	resultsSection: { marginTop: 14, paddingTop: 14, borderTopWidth: 1, borderTopColor: colors.border },
	resultsSectionTitle: { fontSize: 14, fontWeight: '800', color: colors.titleText, marginBottom: 8 },
	resultListItem: { fontSize: 13, color: colors.text, lineHeight: 20, marginBottom: 4 },
	resultsCard: { maxHeight: 420, backgroundColor: colors.secondaryBackground, borderRadius: 8, marginVertical: 16, borderWidth: 1, borderColor: colors.border },
	resultsCardContent: { padding: 20, paddingBottom: 24 },
	resultText: { fontSize: 16, fontWeight: '600', marginVertical: 8, color: colors.text },
	finishButton: { paddingVertical: 12, backgroundColor: colors.success, borderRadius: 8, alignItems: 'center', marginTop: 20 },
	finishButtonText: { fontSize: 16, fontWeight: '700', color: colors.buttonText },
	modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)' },
	mcOption: { flexDirection: 'row', justifyContent: 'space-between', padding: 10, borderRadius: 8, borderWidth: 1, borderColor: colors.border, marginVertical: 4, backgroundColor: colors.secondaryBackground, alignItems: 'center' },
	mcSelected: { borderColor: colors.info, backgroundColor: colors.tertiaryBackground },
	mcCorrect: { borderColor: colors.success, backgroundColor: colors.tertiaryBackground },
	mcIncorrect: { borderColor: colors.danger, backgroundColor: colors.tertiaryBackground },
	challengeButton: { paddingHorizontal: 8, paddingVertical: 6, borderRadius: 8, borderWidth: 1, borderColor: colors.border, marginRight: 6, alignItems: 'center', backgroundColor: colors.secondaryBackground },
	challengeSelected: { borderColor: colors.info, backgroundColor: colors.tertiaryBackground },
	fullscreenIntro: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', alignItems: 'center' },
	introInner: { backgroundColor: colors.secondaryBackground, padding: 24, borderRadius: 8, width: '80%', alignItems: 'center', borderWidth: 1, borderColor: colors.border },
	introTitle: { fontSize: 22, fontWeight: '700', color: colors.titleText },
	surveyType: { fontSize: 20, fontWeight: 'bold', marginBottom: 20, textAlign: 'center', color: colors.titleText },
	goalsScrollView: { maxHeight: 360, borderRadius: 8, marginVertical: 8 },
	arrowRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, marginBottom: 12 },
	arrowBullet: { fontSize: 16, fontWeight: '700', marginTop: 2, color: colors.secondaryText },
	arrowText: { flex: 1, fontSize: 15, lineHeight: 22, color: colors.text },
	inlineInput: { borderWidth: 1, borderColor: colors.border, borderRadius: 8, padding: 10, fontSize: 14, marginTop: 8, backgroundColor: colors.inputBackground, color: colors.text },
});

export const sectionStyles = createSectionStyles(fallbackColors);

export function useSectionStyles() {
	const { colors } = useTheme();
	return useMemo(() => createSectionStyles(colors), [colors]);
}
