import { StyleSheet } from 'react-native';

export const sectionStyles = StyleSheet.create({
	container: { flex: 1, backgroundColor: '#fff' },
	content: { flex: 1, padding: 16 },
	contentArea: { flex: 1 },
	title: { fontSize: 24, fontWeight: 'bold', marginBottom: 20, textAlign: 'center' },
	progressContainer: { paddingHorizontal: 16, marginBottom: 8 },
	progressBar: { height: 8, backgroundColor: '#e0e0e0', borderRadius: 4, overflow: 'hidden', marginBottom: 8 },
	progressFill: { height: '100%', backgroundColor: '#4CAF50' },
	progressText: { fontSize: 12, textAlign: 'right' },
	closeButton: { width: 44, height: 44, justifyContent: 'center', alignItems: 'center', marginLeft: 8 },
	closeButtonText: { fontSize: 28, fontWeight: '300', color: '#666' },
	surveyLabelContainer: { paddingVertical: 12, paddingHorizontal: 16, backgroundColor: '#f0f0f0', borderBottomWidth: 1, borderColor: '#e0e0e0', alignItems: 'center' },
	surveyLabelText: { fontSize: 18, fontWeight: '700', color: '#333' },
	surveyContent: { flex: 1, paddingHorizontal: 16 },
	surveyContentInner: { paddingVertical: 20 },
	listContentContainer: { paddingHorizontal: 16, paddingVertical: 20 },
	question: { fontSize: 18, fontWeight: '600', marginBottom: 16 },
	adviceText: { fontSize: 16, lineHeight: 24, color: '#333', marginBottom: 8 },
	adviceLabel: { fontSize: 13, color: '#999', fontStyle: 'italic' },
	label: { fontSize: 14, fontWeight: '600', color: '#666' },
	textInputArea: { borderWidth: 1, borderColor: '#ccc', borderRadius: 8, padding: 12, minHeight: 100, fontSize: 16 },
	buttonContainer: { flexDirection: 'row', gap: 10, paddingHorizontal: 16, paddingVertical: 12, paddingBottom: 24, borderTopWidth: 1, borderTopColor: '#f0f0f0', backgroundColor: '#fff' },
	buttonPrevious: { flex: 1, paddingVertical: 12, backgroundColor: '#fafafa', borderRadius: 8, alignItems: 'center', borderWidth: 1, borderColor: '#ddd' },
	buttonSmall: { flex: 1, paddingVertical: 12, backgroundColor: '#fafafa', borderRadius: 8, alignItems: 'center', borderWidth: 1, borderColor: '#ddd', marginRight: 8 },
	buttonNext: { flex: 1, paddingVertical: 12, backgroundColor: '#4CAF50', borderRadius: 8, alignItems: 'center' },
	buttonDisabled: { backgroundColor: '#ccc', opacity: 0.6 },
	buttonText: { fontSize: 14, fontWeight: '600', color: '#666' },
	buttonTextPrimary: { fontSize: 14, fontWeight: '600', color: '#fff' },
	smallButton: { paddingVertical: 8, paddingHorizontal: 12, backgroundColor: '#eee', borderRadius: 8, alignSelf: 'flex-start', marginTop: 8 },
	smallButtonText: { fontSize: 13, fontWeight: '600', color: '#333' },
	rerollButton: { paddingVertical: 10, paddingHorizontal: 12, backgroundColor: '#e3f2fd', borderRadius: 8, alignSelf: 'flex-start', marginTop: 12 },
	rerollButtonText: { fontSize: 13, fontWeight: '600', color: '#1976d2' },
	miniButton: { width: 32, height: 32, borderRadius: 6, justifyContent: 'center', alignItems: 'center' },
	miniEditButton: { backgroundColor: '#2196F3' },
	miniButtonText: { fontSize: 14, color: '#fff' },
	moodGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, justifyContent: 'space-between' },
	moodButton: { width: '30%', padding: 10, borderRadius: 8, borderWidth: 1, borderColor: '#ddd', alignItems: 'center', marginBottom: 8 },
	moodSelected: { borderColor: '#4CAF50', backgroundColor: '#eefaf0' },
	moodEmoji: { fontSize: 24, marginBottom: 6 },
	moodLabel: { fontSize: 12, textAlign: 'center' },
	habitRow: { padding: 12, borderRadius: 8, borderWidth: 1, borderColor: '#eee', marginBottom: 8, backgroundColor: '#fff' },
	habitImportant: { borderColor: '#FFB74D', backgroundColor: '#FFF8E1' },
	habitImportantPlus: { borderColor: '#FF8A65', backgroundColor: '#FFF3E0' },
	habitTitle: { fontSize: 16, fontWeight: '600' },
	habitMeta: { fontSize: 12, color: '#666', marginTop: 4 },
	challengeRow: { padding: 12, borderRadius: 8, borderWidth: 1, borderColor: '#d0e8ff', marginBottom: 8, backgroundColor: '#f3f9ff' },
	habitCompleted: { borderColor: '#4CAF50', backgroundColor: '#E8F5E9' },
	suggestedScrollView: { maxHeight: 300, borderRadius: 8, borderWidth: 1, borderColor: '#f0f0f0' },
	suggestedItem: { padding: 10, borderBottomWidth: 1, borderBottomColor: '#f5f5f5' },
	todoItem: { padding: 12, borderRadius: 8, borderWidth: 1, borderColor: '#eee', marginBottom: 8, backgroundColor: '#fff' },
	todoImportant: { borderColor: '#FFB74D', backgroundColor: '#FFF8E1' },
	todoImportantPlus: { borderColor: '#FF8A65', backgroundColor: '#FFF3E0' },
	todoCompleted: { borderColor: '#4CAF50', backgroundColor: '#E8F5E9' },
	subGoalRow: { paddingLeft: 12, paddingVertical: 6 },
	resultsCard: { backgroundColor: '#f5f5f5', borderRadius: 12, padding: 20, marginVertical: 16 },
	resultText: { fontSize: 16, fontWeight: '600', marginVertical: 8 },
	finishButton: { paddingVertical: 12, backgroundColor: '#4CAF50', borderRadius: 8, alignItems: 'center', marginTop: 20 },
	finishButtonText: { fontSize: 16, fontWeight: '700', color: '#fff' },
	modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)' },
	mcOption: { flexDirection: 'row', justifyContent: 'space-between', padding: 10, borderRadius: 8, borderWidth: 1, borderColor: '#ddd', marginVertical: 4, backgroundColor: '#fff', alignItems: 'center' },
	mcSelected: { borderColor: '#2196F3', backgroundColor: '#e3f2fd' },
	mcCorrect: { borderColor: '#4CAF50', backgroundColor: '#e8f5e9' },
	mcIncorrect: { borderColor: '#e74c3c', backgroundColor: '#fadbd8' },
	challengeButton: { paddingHorizontal: 10, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: '#ddd', marginRight: 8, alignItems: 'center' },
	challengeSelected: { borderColor: '#1976d2', backgroundColor: '#e3f2fd' },
	fullscreenIntro: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', alignItems: 'center' },
	introInner: { backgroundColor: '#fff', padding: 24, borderRadius: 16, width: '80%', alignItems: 'center' },
	introTitle: { fontSize: 22, fontWeight: '700' },
	surveyType: { fontSize: 20, fontWeight: 'bold', marginBottom: 20, textAlign: 'center' },
	goalsScrollView: { maxHeight: 250, borderRadius: 8, marginVertical: 8 },
	arrowRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, marginBottom: 12 },
	arrowBullet: { fontSize: 16, fontWeight: '700', marginTop: 2 },
	arrowText: { flex: 1, fontSize: 15, lineHeight: 22 },
	inlineInput: { borderWidth: 1, borderColor: '#ddd', borderRadius: 8, padding: 10, fontSize: 14, marginTop: 8 },
});
